Final-App/config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
	  root 'devise/sessions#new'
  end
  # User
  resources :users do
    resources :albums
    resources :photos
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Resourceful

  # Admin
  namespace :admin do
  	resources :users, :photos, :albums, only: [:show, :edit, :update, :destroy]
  end

  # Albums
  # namespace :albums do
  #   resources :photos, only: [:edit, :update, :show, :destory]
  # end
  # resources :albums
  # resources :users, only: [:new, :create, :show]

  # Non-resourceful
  # Signup
  # root 'users#new'
  # post 'users/new', to: 'users#create'
  #Signin
  # root 'home#create'
  # get '/exit', to: 'session#destroy', as: :logout

end

Final-App/app/models/User.rb
class User < ApplicationRecord

	# Active Record Validation
	validates :first_name, :last_name, length: {
		maximum: 25,
		presence: true,
		too_long: "maximum 25 characters long"
	},
	format: { 
		with: /\A[a-zA-Z]+\z/,
		message: "only alows characters"
	}

	validates :email, length: {
		maximum: 255,
		presence: true,
		too_long: "maximum 255 characters long"
	},
	uniqueness: {
		case_sensitive: true,
		message: "this email has already been taken"
	},
	email: true # for validate email
	validates :password, length: {
		maximum: 64,
		presence: true,
		too_long: "maximum 64 characters long"
	}

	# Active Record Association
	has_many :albums, dependent: :destroy
	has_many :photos, dependent: :destroy

	# Has many users follow me
	has_many :received_follows, foreign_key: :followed_user_id, class_name: "Follow"
	has_many :followers, through: :received_follows, source: :follower

	# Me follows many users
	has_many :given_follows, foreign_key: :follower_id, class_name: "Follow"
	has_many :followings, through: :given_follows, source: :followed_user

	# User has many likes
	has_many :likes, dependent: :destroy

end

Final-App/app/models/user.rb
class User < ApplicationRecord
	# Devise modules
	devise :database_authenticatable, :registerable, :recoverable, :rememberable, :confirmable, :validatable, :timeoutable

	# Active Record Validation
	validates :first_name, :last_name, length: {
		maximum: 25,
		presence: true,
		too_long: "maximum 25 characters long"
	},
	format: { 
		with: /\A[a-zA-Z]+\z/,
		message: "only alows characters"
	}

	validates :email, length: {
		maximum: 255,
		presence: true,
		too_long: "maximum 255 characters long"
	},
	uniqueness: {
		case_sensitive: true,
		message: "this email has already been taken"
	},
	email: true # for validate email
	validates :password, length: {
		maximum: 64,
		presence: true,
		too_long: "maximum 64 characters long"
	}

	# Active Record Association
	has_many :albums, dependent: :destroy
	has_many :photos, dependent: :destroy

	# Has many users follow me
	has_many :received_follows, foreign_key: :followed_user_id, class_name: "Follow"
	has_many :followers, through: :received_follows, source: :follower

	# Me follows many users
	has_many :given_follows, foreign_key: :follower_id, class_name: "Follow"
	has_many :followings, through: :given_follows, source: :followed_user

	# User has many likes
	has_many :likes, dependent: :destroy

end

Final-App/app/controllers/user_controller.rb
class UserController < ApplicationController
	def index
	end

	def create
		@user = User.create(user_params)
		save = @user.save
		if save
			UserMailer.with(user: @user).welcome_email.deliver_later
			render "show"
		else
			puts @user.errors.messages
			redirect_to user_index_path
		end
	end

	def show
	end

	private
		def user_params
			params.permit(:first_name, :last_name, :email, :password)
		end
end

Final-App/app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, :find_user, only: [:edit, :show]

	def new
		@user = User.new
	end

	def create
		@user = User.create(user_params)
		save = @user.save
		if save
			# UserMailer.with(user: @user).welcome_email.deliver_later
			SendMailLaterJob.perform_later(@user)
			render 'show'
		else
			puts @user.email
			puts @user.errors.messages
			redirect_to new_user_path
		end
	end

	def edit
	end

	def show
		#Get following users
		@following_users = @user.followings

		# Get photos/albums from following users
		@following_photos = []
		@following_albums = []

		@following_users.each do |user| @following_photos += Photo.joins(:user).where("photos.user_id = ? AND photos.sharing_mode = ?", user.id, "public") end
		@following_photos = @following_photos.sort_by(&:created_at).reverse

		@following_users.each do |user| @following_albums += Album.joins(:user).where("albums.user_id = ? AND albums.sharing_mode = ?", user.id, "public") end
		@following_albums = @following_albums.sort_by(&:created_at).reverse
	end

	def destroy
		redirect_to root_path
	end

	def find_user
		@user = User.find(params[:id])
	end

	private
		def user_params
			params.require(:user).permit(:first_name, :last_name, :email, :password)
		end
end

Final-App/app/helpers/user_helper.rb
module UserHelper
end

Final-App/app/helpers/users_helper.rb
module UsersHelper
end

Final-App/app/views/users/_feed_albums.html.erb
<!-- Album Modal -->
<div class="modal fade" id="photo-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="photo-modal">hmm</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
					<div class="carousel-inner">
						<div class="carousel-item active">
							<%= image_tag("desktop.jpg", class: "img-fluid", alt: "Card image cap") %>
						</div>
						<div class="carousel-item">
							<%= image_tag("desktop.jpg", class: "img-fluid", alt: "Card image cap") %>
						</div>
						<div class="carousel-item">
							<%= image_tag("desktop.jpg", class: "img-fluid", alt: "Card image cap") %>
						</div>
					</div>
					<a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
						<span class="carousel-control-prev-icon" aria-hidden="true"></span>
						<span class="sr-only">Previous</span>
					</a>
					<a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
						<span class="carousel-control-next-icon" aria-hidden="true"></span>
						<span class="sr-only">Next</span>
					</a>
				</div>
				<hr>
				<p>hmm</p>
			</div>

			<div class="modal-footer">
				<p>hmm</p>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<% if @user.followings.length != 0 %>
		<% @following_albums.each do |album| %>
			<div class="col-xs-12 col-md-6 p-3">
				<div class="card bg-light border-light ml-2">
					<div class="row py-0 px-2">
						<div class="col-xs-12 col-md-6 p-0">
							<%= image_tag("desktop.jpg", class: "position-absolute img-fluid img-thumbnail album-imgs", data: {toggle: "modal", target: "#photo-modal"}, alt: "Card image cap") %>
							<%= image_tag("desktop.jpg", class: "position-absolute rotate6 img-fluid img-thumbnail album-imgs", data: {toggle: "modal", target: "#photo-modal"}, alt: "Card image cap") %>
							<%= image_tag("desktop.jpg", class: "rotate11 img-fluid img-thumbnail album-imgs", alt: "Card image cap") %>
						</div>

						<div class="col-xs-12 col-md-6 pl-4">
							<div class="card-title">
								<%image_tag("tuanminh.png", class: "img-fluid rounded-circle ft-avatar", alt: "user-avatar") %>
								<span class="font-weight-bold ft-login" href="#"> <%=album.user.first_name %> <%= album.user.last_name%> </span>
								<p><strong> <%= album.title %> </strong></p>
							</div>

							<div class="card-body px-0">
								<p class="card-text"> <%= album.description %> </p>
							</div>

							<span><button class="heart-btn px-0" ><i class="fas fa-heart"></i></button></span>
							<span class="like-numbers">112</span>
							<span class="offset-md-2 font-italic ft-date"> <%= album.created_at.localtime %> </span>
						</div>
					</div>
				</div>
			</div>
		<% end %>
	<% else %>
		<div class="col-12 col-md-12">
			<p class="text-center">You have not followed anyone yet!</p>
		</div>
	<% end %>
</div>

Final-App/app/views/users/_form.html.erb
<%#= form_with model: @user, local: true, :html => {:class => "form-signin"} do |u| %>
	<%#= u.label :first_name, "First Name:", :class => "font-weight-bold" %>
  	<%#= u.text_field :first_name, :value => "", :placeholder => "Enter First Name", :class => "form-control", required: 'true'%>

	<%#= u.label :last_name, "Last Name:", :class => "font-weight-bold" %>
	<%#= u.text_field :last_name, :value => "", :placeholder => "Enter Last Name", :class => "form-control", required: 'true'%>

	<%#= u.label :email, "Email:", :class => "font-weight-bold" %>
	<%#= u.text_field :email, :value => "", :placeholder => "Enter Email", :class => "form-control", required: 'true'%>

	<%#= u.label :password, "Password:", :class => "font-weight-bold" %>
	<%#= u.password_field :password, :value => "", :placeholder => "Enter Password", :class => "form-control", required: 'true'%>

<!--	<div class="text-center">-->
		<%#= u.submit "Signup", :class => "mt-2 mb-2 btn text-light login-btn" %>
<!--	</div>-->
<%# end %>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name), local: true, :html => {:class => "form-signin"}) do |u| %>
	<%= render "users/shared/error_messages", resource: resource %>

	<%= u.label :first_name, "First Name:", :class => "font-weight-bold" %>
	<%= u.text_field :first_name, :value => "", :placeholder => "Enter First Name", :class => "form-control", required: 'true'%>

	<%= u.label :last_name, "Last Name:", :class => "font-weight-bold" %>
	<%= u.text_field :last_name, :value => "", :placeholder => "Enter Last Name", :class => "form-control", required: 'true'%>

	<%= u.label :email, "Email:", :class => "font-weight-bold" %>
	<%= u.email_field :email, autofocus: true, autocomplete: "email", :value => "", :placeholder => "Enter Email", :class => "form-control", required: 'true'%>

	<%= u.label :password, "Password:", :class => "font-weight-bold" %>
	<% if @minimum_password_length %>
		<em>(<%= @minimum_password_length %> characters minimum)</em>
	<% end %><br />
	<%= u.password_field :password, autocomplete: "new-password", :value => "", :placeholder => "Enter Password", :class => "form-control", required: 'true'%>

	<%= u.label :password_confirmation, "Password:", :class => "font-weight-bold" %>
	<%= u.password_field :password_confirmation, autocomplete: "new-password", :value => "", :placeholder => "Enter Password", :class => "form-control", required: 'true'%>

	<div class="text-center">
		<%= u.submit "Signup", :class => "mt-2 mb-2 btn text-light login-btn" %>
	</div>
<% end %>

<%= render "users/shared/links" %>

Final-App/app/views/users/edit.html.erb
<!doctype html>
<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Google Roboto Font -->
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet" type="text/css">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<!-- add after bootstrap.min.css -->
	<link rel="stylesheet" href="https://cdn.rawgit.com/afeld/bootstrap-toc/v0.3.0/dist/bootstrap-toc.min.css">
	<%= stylesheet_link_tag 'style' %>

	<title></title>
</head>
<body data-spy="scroll" data-target="#toc" class="ft-mainpage">

<nav class="navbar navbar-expand-lg fixed-top navbar-dark ft-navbar">
	<div class="col-xs-1 col-md-1 offset-md-1 text-center">
		<a class="navbar-brand ft-name font-weight-bold" href="#">Fotobook</a>
	</div>

	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<div class="col-md-5 mr-auto px-0">
			<div class="input-group input-group-sm">
				<input class="form-control" type="search" role="search" placeholder="Search Photo / Album" aria-label="Search">
			</div>
		</div>

		<div class="col-xs-6 col-md-1 text-center">
			<a class="navbar-brand" href="#">
				<%= image_tag("tuanminh.png", class: "img-fluid rounded-circle ft-avatar", alt: "user-avatar") %>
				<span class="font-weight-bold ft-login" href="#"> <%= @user.first_name %> <%= @user.last_name%> </span>
			</a>
		</div>

		<div class="col-xs-6 col-md-2 text-center">
			<a class="navbar-brand font-weight-bold ft-login" href="#">Logout</a>
		</div>
	</div>
</nav>

<div class="container-fluid ">
	<div class="row">
		<div class="col-xs-1 col-md-2 mt-5">
			<nav class="sticky-top text-center" id="toc" data-toggle="toc">
				<ul class="nav navbar-nav">
					<button type="button" class="btn shadow-none content-text">Feeds</button>
				</ul>
				<ul class="nav navbar-nav">
					<button type="button" class="btn shadow-none content-text">Discovery</button>
				</ul>
			</nav>
		</div>

		<main class="col-xs-6 col-md-8 bg-white mt-3 hmm">

			<div class="row justify-content-center">
				<div class="col-5 col-md-2 pt-4 pl-4">
					<%= image_tag("profile.png", class: "img-fluid ft-profile-img", alt: "profile-avatar") %>
				</div>

				<div class="col-7 col-md- p-0">
					<span class="badge badge-pill badge-warning text-white font-weight-bold px-3 pt-1 mt-4 ml-1">Following</span>
					<a href="#">
						<p class="pt-3 pl-2 h1 text-dark font-weight-bolder"> <%= @user.first_name%> <%= @user.last_name%></p>
					</a>

					<div class="row px-3">
						<div class="col-10 col-md-3 border-right border-secondary">
							<a class="photo-text font-weight-bold">108 <small>PHOTOS</small></a>
						</div>

						<div class="col-10 col-md-3 border-right border-secondary">
							<a class="photo-text font-weight-bold disabled">43 <small>ALBUMS</small></a>
						</div>

						<div class="col-10 col-md-3 border-right border-secondary">
							<a class="photo-text font-weight-bold disabled">22 <small>FOLLOWINGS</small></a>
						</div>

						<div class="col-10 col-md-3 border-right border-secondary">
							<a class="photo-text font-weight-bold disabled">13 <small>FOLLOWERS</small></a>
						</div>
					</div>
				</div>
			</div>

			<div class="float-md-right">
<!--				<button type="button" class="btn btn-sm m-3 px-3 btn-success">Add Photo</button>-->
				<%= link_to("Add Photo", new_user_photo_path(user_id: @user.id), class: "btn btn-sm m-3 px-3 btn-success")%>
			</div>

			<div class="row mt-5 justify-content-center">
				<div class="col-xs-1 col-md-2 m-4 p-0">
					<div class="col-md-12 p-0 border">
						<img class="img-fluid ft-imgs" src="5wgCcaI.gif" alt="photo">
					</div>
					<figcaption class="text-center small text-secondary border-0">Photo Titles go here</figcaption>
				</div>

				<div class="col-xs-1 col-md-2 m-4 p-0">
					<div class="col-md-12 p-0 border">
						<img class="img-fluid ft-imgs" src="5wgCcaI.gif" alt="photo">
					</div>
					<figcaption class="text-center small text-secondary border-0">Photo Titles go here</figcaption>
				</div>

				<div class="col-xs-1 col-md-2 m-4 p-0">
					<div class="col-md-12 p-0 border">
						<img class="img-fluid ft-imgs" src="5wgCcaI.gif" alt="photo">
					</div>
					<figcaption class="text-center small text-secondary border-0">Photo Titles go here</figcaption>
				</div>

				<div class="col-xs-1 col-md-2 m-4 p-0">
					<div class="col-md-12 p-0 border">
						<img class="img-fluid ft-imgs" src="5wgCcaI.gif" alt="photo">
					</div>
					<figcaption class="text-center small text-secondary border-0">Photo Titles go here</figcaption>
				</div>

				<div class="col-xs-1 col-md-2 m-4 p-0">
					<div class="col-md-12 p-0 border">
						<img class="img-fluid ft-imgs" src="5wgCcaI.gif" alt="photo">
					</div>
					<figcaption class="text-center small text-secondary border-0">Photo Titles go here</figcaption>
				</div>

				<div class="col-xs-1 col-md-2 m-4 p-0">
					<div class="col-md-12 p-0 border">
						<img class="img-fluid ft-imgs" src="5wgCcaI.gif" alt="photo">
					</div>
					<figcaption class="text-center small text-secondary border-0">Photo Titles go here</figcaption>
				</div>

				<div class="col-xs-1 col-md-2 m-4 p-0">
					<div class="col-md-12 p-0 border">
						<img class="img-fluid ft-imgs" src="5wgCcaI.gif" alt="photo">
					</div>
					<figcaption class="text-center small text-secondary border-0">Photo Titles go here</figcaption>
				</div>

				<div class="col-xs-1 col-md-2 m-4 p-0">
					<div class="col-md-12 p-0 border">
						<img class="img-fluid ft-imgs" src="5wgCcaI.gif" alt="photo">
					</div>
					<figcaption class="text-center small text-secondary border-0">Photo Titles go here</figcaption>
				</div>

				<div class="col-xs-1 col-md-2 m-4 p-0">
					<div class="col-md-12 p-0 border">
						<img class="img-fluid ft-imgs" src="5wgCcaI.gif" alt="photo">
					</div>
					<figcaption class="text-center small text-secondary border-0">Photo Titles go here</figcaption>
				</div>

				<div class="col-xs-1 col-md-2 m-4 p-0">
					<div class="col-md-12 p-0 border">
						<img class="img-fluid ft-imgs" src="5wgCcaI.gif" alt="photo">
					</div>
					<figcaption class="text-center small text-secondary border-0">Photo Titles go here</figcaption>
				</div>
			</div>


			<footer>
				<nav aria-label="Page navigation example">
					<ul class="pagination m-3 justify-content-center">
						<li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
						<li class="page-item active"><a class="page-link" href="#">1</a></li>
						<li class="page-item"><a class="page-link" href="#">2</a></li>
						<li class="page-item"><a class="page-link" href="#">3</a></li>
						<li class="page-item"><a class="page-link" href="#">Next</a></li>
					</ul>
				</nav>
			</footer>
		</main>

		<div class="col-xs-1 col-md-2">

		</div>
	</div>

</div>



<!-- Font Awesome -->
<script src="https://kit.fontawesome.com/1fb1fb2be8.js" crossorigin="anonymous"></script>

<!-- Optional JavaScript -->

<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
<!-- add after bootstrap.min.js -->
<script src="https://cdn.rawgit.com/afeld/bootstrap-toc/v0.3.0/dist/bootstrap-toc.min.js"></script>

<script src="src.js"></script>
</body>
</html>

Final-App/app/views/users/show.html.erb
<!doctype html>
<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Google Roboto Font -->
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet" type="text/css">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<!-- add after bootstrap.min.css -->
	<link rel="stylesheet" href="https://cdn.rawgit.com/afeld/bootstrap-toc/v0.3.0/dist/bootstrap-toc.min.css">
	<%= stylesheet_link_tag 'style' %>

	<title>Fotobook</title>
</head>
<body data-spy="scroll" data-target="#toc" class="ft-mainpage">

<nav class="navbar navbar-expand-lg fixed-top navbar-dark ft-navbar">
	<div class="col-xs-1 col-md-1 offset-md-1 text-center">
		<a class="navbar-brand ft-name font-weight-bold" href="#">Fotobook</a>
	</div>

	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<div class="col-md-5 mr-auto px-0">
			<div class="input-group input-group-sm">
				<input class="form-control" type="search" role="search" placeholder="Search Photo / Album" aria-label="Search">
			</div>
		</div>

		<div class="col-xs-6 col-md-1 text-center">
			<%= link_to(edit_user_path, class: "navbar-brand") do  %>
				<%= image_tag("tuanminh.png", class: "img-fluid rounded-circle ft-avatar") %>
				<span class="font-weight-bold ft-login" href="#"> <%= @user.first_name %> <%=@user.last_name %> </span>
			<% end %>
		</div>

		<div class="col-xs-6 col-md-2 text-center">
			<%= link_to("Logout", destroy_user_session_path, method: "delete", class: "navbar-brand font-weight-bold ft-login") %>
		</div>
	</div>
</nav>

<div class="container-fluid ">
	<div class="row">
		<div class="col-xs-1 col-md-2 mt-5">
			<nav class="sticky-top text-center" id="toc" data-toggle="toc">
				<ul class="nav navbar-nav">
					<button type="button" class="btn shadow-none p-0 content-text content-text-active">Feeds</button>
				</ul>

				<ul class="nav navbar-nav">
					<button type="button" class="btn shadow-none p-0 content-text">Discovery</button>
				</ul>
			</nav>
		</div>

		<main class="col-xs-6 col-md-8 bg-white mt-3 hmm">
			<div class="row">
				<div class="btn-group mx-auto m-3">
					<button type="button" class="btn ft-button active">
						PHOTO
					</button>

					<button type="button" class="btn ft-button">
						ALBUM
					</button>
				</div>
			</div>
			<%= render "feed_photos" %>
			<%#= render "feed_albums" %>

			<div class="d-flex justify-content-center">
				<div class="spinner-border" role="status">
					<span class="sr-only">Loading...</span>
				</div>
			</div>

			<footer>
				<nav aria-label="Page navigation example">
					<ul class="pagination m-3 justify-content-center">
						<li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
						<li class="page-item active"><a class="page-link" href="#">1</a></li>
						<li class="page-item"><a class="page-link" href="#">2</a></li>
						<li class="page-item"><a class="page-link" href="#">3</a></li>
						<li class="page-item"><a class="page-link" href="#">Next</a></li>
					</ul>
				</nav>
			</footer>

		</main>

		<div class="col-xs-1 col-md-2">

		</div>
	</div>

</div>



<!-- Font Awesome -->
<script src="https://kit.fontawesome.com/1fb1fb2be8.js" crossorigin="anonymous"></script>

<!-- Optional JavaScript -->

<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
<!-- add after bootstrap.min.js -->
<script src="https://cdn.rawgit.com/afeld/bootstrap-toc/v0.3.0/dist/bootstrap-toc.min.js"></script>

<%= javascript_include_tag 'src' %>
</body>
</html>